#!/usr/bin/env bash
# Stop hook — regenerate core/hot/handoff.md from recent.md.
# handoff.md is the compact "last 10 entries" file loaded into context on
# the next session start (via @core/hot/handoff.md in CLAUDE.md).
set +e

WS="${AGENT_WORKSPACE:-${HOME}/.claude-lab/$(basename "$(dirname "$(dirname "$(realpath "$0")")")")/.claude}"
HOT="${WS}/core/hot/recent.md"
HANDOFF="${WS}/core/hot/handoff.md"

[ -f "$HOT" ] || exit 0

# Find the offsets of every "### " heading; keep the last 10.
HEADINGS=$(grep -n '^### ' "$HOT" || true)
[ -z "$HEADINGS" ] && exit 0

LAST10=$(echo "$HEADINGS" | tail -n 10)
START_LINE=$(echo "$LAST10" | head -n 1 | cut -d: -f1)

[ -z "$START_LINE" ] && exit 0

{
    echo "# HOT handoff — last 10 entries"
    echo ""
    echo "_Loaded into the next session context via \`@core/hot/handoff.md\`._"
    echo "_Regenerated by \`write-handoff.sh\` on Stop._"
    echo ""
    tail -n +"$START_LINE" "$HOT"
} >"$HANDOFF" 2>/dev/null

exit 0
